---
title: "Heatmap of SnC vs non-SnC DE Secreted genes"
author: "Sushma Nagaraj"
date: "2024-10-25"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(purrr)
  library(tidyverse)
  library(stringr)
  library(ComplexHeatmap)
  library(circlize)
})

here::i_am("2_SnC_cell_analysis/heatmap_SnC_vs_nonSnC_FC.secreted.Rmd")
```

## Clusters of interest
```{r}
SnC_clusters <- c("Fibroblast", "Pericyte_SMC", "Lymphatic_endo", "Endo_vein2")
tissue <- "fibroid"
```


## SnC vs non-SnC Findmarkers result thresholded on p-value and FC
```{r}
de_genes_list <- lapply(SnC_clusters, function(clust) {
  SnC.genes <- read.csv(here::here("results", "2_SnC-vs-nonSnC", tissue, paste0(tissue, ".", clust, ".SnC.genes.csv")), row.names = 1)
  SnC.genes <- SnC.genes %>%
    #filter(p_val_adj < 0.05) %>%
    filter(p_val_adj < 0.05 & abs(avg_log2FC) > 0.3) 
})
names(de_genes_list) <- SnC_clusters
```


## Genes to plot
```{r}
de_genes_list.sub <- lapply(seq_along(de_genes_list), function(x) {
  de <- de_genes_list[[x]] %>%
    filter(cpdb.secreted) %>%
    rownames_to_column()
  de
})
names(de_genes_list.sub) <- names(de_genes_list)
de_genes_interesting <- list_rbind(de_genes_list.sub, names_to = "cell_type") 
de_genes_interesting$cell_type <- paste0("SnC.", de_genes_interesting$cell_type)
```

## Create LFC data matrix to plot
```{r}
dat.wide <- de_genes_interesting %>%
  pivot_wider(id_cols = rowname, 
              names_from = cell_type, 
              values_from = avg_log2FC) %>%
  column_to_rownames()

dat.wide[is.na(dat.wide)] <- 0

head(dat.wide)
```


# Heatmap annotation
## Column annotation
```{r}
#Cell type 
celltype <- colnames(dat.wide)
names(celltype) <- celltype
celltype

cell_col <- c("#E69F00", "#56B4E9", "#FFCB57", "#00EEB0")
names(cell_col) <- c("SnC.Fibroblast", "SnC.Pericyte_SMC", "SnC.Lymphatic_endo", "SnC.Endo_vein2")
cell_col

sample_anno <- HeatmapAnnotation(
  Celltype = celltype,
  col = list(Celltype = cell_col)
)
```

## Row annotation
```{r}
ann <- de_genes_interesting %>%
  select(c(rowname, cpdb.secreted, Category, Category.KEGG)) %>%
  unique()
rownames(ann) <- ann$rowname

sec_ligands <- read.csv(here::here("results", "2_SnC-vs-nonSnC", tissue, "secreted_ligands.annotated.csv"), header = TRUE, row.names = 1)
head(sec_ligands)

ann$Plot.categories <- sec_ligands[match(ann$rowname, sec_ligands$X), "Plot.categories"] 
table(ann$Plot.categories)

ann$Plot.categories <- factor(ann$Plot.categories, levels = c("ECM component", "ECM remodeling", "Growth factor", "Cytokine", "Chemokine", "TGF-beta superfamily", "TNF superfamily", "Development", "Angiogenesis", "Cell regulation", "Cell adhesion", "Hormone precursor", "Homeostasis regulator", "Hemostasis", "Wnt signaling modulator", "Intracellular transport", "Protein degradation", "Iron uptake"))

all(ann$rowname == rownames(dat.wide))
```

## Heatmap
```{r}
ht <- Heatmap(as.matrix(dat.wide), 
        col = colorRamp2(c(-2.5, 0, 2.5), colors = c("blue", "whitesmoke", "red")), 
        name = "avg_log2FC", 
        show_column_names = F, 
        top_annotation = sample_anno, 
        cluster_columns = T, 
        cluster_rows = T, 
        show_row_dend = F, 
        show_column_dend = F,
        row_names_gp = gpar(fontsize = 8),
        column_title_rot = 50,
        row_title_rot = 0,
        row_split = ann$Plot.categories,
        row_gap = unit(3, "mm"),
        column_split = celltype
)
```

## Save plot
```{r, fig.height=13}
#pdf(here::here("plots_for_figures", "plots", "Fig_2", "Heatmap.SnC_vs_nonSnC_FC.secreted.pdf"), width = 6.5, height = 13)
ht
#dev.off()
```


```{r}
sessionInfo()
```

